name: simulations
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - pytest
  - r-base
  - r-ecp
  - rpy2
  - changeforest
  - scikit-learn  # For adj. rand
  - numpy
  - pandas  # For read.csv only. TODO: get rid of this