name: simulations
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - pytest
  - r-base
  - r-ecp
  - r-rfast  # for Rfast::Lchoose only
  - r-kernlab  # Dependency of r-KernSeg
  - ruptures
  - rpy2
  - changeforest
  - scikit-learn  # For adj. rand
  - numpy
  - openpyxl  # To read dry-beans excel file
  - pandas  # For read.csv only. TODO: get rid of this
  - click