name: simulations
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - pytest
  - r-base
  - r-ecp
  - r-rfast  # for Rfast::Lchoose only
  - ruptures
  - rpy2
  - changeforest=0.6.0
  - scikit-learn  # For adj. rand
  - numpy
  - scipy>=1.5  # mad
  - openpyxl  # To read dry-beans excel file
  - pandas
  - click
  - matplotlib