on:
  push:
    branches: [ main ]
  pull_request:

name: CI

jobs:
  python-tests:
    name: Python tests
    runs-on: ubuntu-latest
    container: condaforge/mambaforge

    steps:
      - uses: actions/checkout@v2
      - name: Set up conda env
        run: |
          mamba env create -f environment.yaml

          # set up conda activate
          CONDA_BASE=$(conda info --base)
          source ${CONDA_BASE}/etc/profile.d/conda.sh

          # Hack from https://github.com/conda/conda/issues/8186
          set +eu
          conda activate simulations
          set -eu
        shell: bash -lxeu {0}

      - name: Install R packages
        run: |
          Rscript install_packages.R  # Some packages are not available on conda-forge

      - name: pip-install package
        run: |
          pip install --no-use-pep517 --no-deps --disable-pip-version-check -e .
      
      - name: Run tests
        run: |
          pytest tests

  pre-commit-checks:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.head_ref }}
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run pre-commit checks
        uses: pre-commit/action@v2.0.3